CREATE TABLE sys_user (
  id BIGINT NOT NULL,
  username VARCHAR(64) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  real_name VARCHAR(64) NOT NULL,
  mobile VARCHAR(20) DEFAULT NULL,
  email VARCHAR(128) DEFAULT NULL,
  role_code VARCHAR(64) NOT NULL DEFAULT 'EMPLOYEE',
  status TINYINT NOT NULL DEFAULT 1,
  last_login_time DATETIME(3) DEFAULT NULL,
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  is_deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_sys_user_username (username),
  UNIQUE KEY uk_sys_user_mobile (mobile),
  KEY idx_sys_user_role_status (role_code, status),
  KEY idx_sys_user_is_deleted (is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE audit_task (
  id BIGINT NOT NULL,
  task_no VARCHAR(50) NOT NULL,
  task_name VARCHAR(200) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  file_storage_type VARCHAR(20) NOT NULL DEFAULT 'LOCAL',
  file_path VARCHAR(1024) NOT NULL,
  file_sha256 CHAR(64) DEFAULT NULL,
  file_size BIGINT DEFAULT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  progress TINYINT NOT NULL DEFAULT 0,
  initiator_user_id BIGINT NOT NULL,
  python_job_id VARCHAR(64) DEFAULT NULL,
  ai_model VARCHAR(100) DEFAULT NULL,
  risk_total INT NOT NULL DEFAULT 0,
  high_risk_count INT NOT NULL DEFAULT 0,
  medium_risk_count INT NOT NULL DEFAULT 0,
  low_risk_count INT NOT NULL DEFAULT 0,
  error_code VARCHAR(64) DEFAULT NULL,
  error_message VARCHAR(1000) DEFAULT NULL,
  start_time DATETIME(3) DEFAULT NULL,
  complete_time DATETIME(3) DEFAULT NULL,
  ext_json JSON DEFAULT NULL,
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  is_deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_audit_task_task_no (task_no),
  KEY idx_audit_task_initiator_status (initiator_user_id, status),
  KEY idx_audit_task_status_ctime (status, create_time),
  KEY idx_audit_task_python_job_id (python_job_id),
  KEY idx_audit_task_is_deleted (is_deleted),
  CONSTRAINT fk_audit_task_initiator FOREIGN KEY (initiator_user_id) REFERENCES sys_user (id),
  CONSTRAINT chk_audit_task_progress CHECK (progress BETWEEN 0 AND 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE audit_risk_item (
  id BIGINT NOT NULL,
  task_id BIGINT NOT NULL,
  seq_no INT NOT NULL DEFAULT 1,
  risk_type VARCHAR(64) NOT NULL,
  risk_level VARCHAR(16) NOT NULL,
  risk_score DECIMAL(5,2) DEFAULT NULL,
  clause_title VARCHAR(255) DEFAULT NULL,
  clause_position VARCHAR(128) DEFAULT NULL,
  page_no INT DEFAULT NULL,
  contract_excerpt TEXT NOT NULL,
  risk_desc VARCHAR(2000) DEFAULT NULL,
  suggestion TEXT NOT NULL,
  legal_basis VARCHAR(500) DEFAULT NULL,
  evidence TEXT DEFAULT NULL,
  review_status TINYINT NOT NULL DEFAULT 0,
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  is_deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_audit_risk_item_task_id (task_id),
  KEY idx_audit_risk_item_level (risk_level),
  KEY idx_audit_risk_item_type (risk_type),
  KEY idx_audit_risk_item_task_deleted (task_id, is_deleted),
  CONSTRAINT fk_risk_item_task FOREIGN KEY (task_id) REFERENCES audit_task (id),
  CONSTRAINT chk_risk_level CHECK (risk_level IN ('HIGH', 'MEDIUM', 'LOW'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE audit_callback_log (
  id BIGINT NOT NULL,
  task_id BIGINT NOT NULL,
  callback_id VARCHAR(64) NOT NULL,
  python_job_id VARCHAR(64) DEFAULT NULL,
  callback_status TINYINT NOT NULL DEFAULT 1,
  http_status INT DEFAULT NULL,
  payload_json JSON NOT NULL,
  fail_reason VARCHAR(1000) DEFAULT NULL,
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  is_deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_callback_id (callback_id),
  KEY idx_callback_task_id (task_id),
  KEY idx_callback_create_time (create_time),
  CONSTRAINT fk_callback_task FOREIGN KEY (task_id) REFERENCES audit_task (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
